# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Create and publish a Docker image
# eu.gcr.io/malte-cloud-run-demo/cluster-demo-app
on:
  push:
    tags:
      - 'v*'

env:
  REGISTRY: eu.gcr.io
  PROJECT_ID: malte-cloud-run-demo
  IMAGE_NAME: cluster-demo-app


jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Google Cloud Credentials
        uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.DEPLOY_KEY }}
          project_id: ${{ env.PROJECT_ID }}
          export_default_credentials: true

      # Make the Google Artifact Registry available to Docker
      - name: Setup to use Google Artifact Registry
        run: gcloud auth configure-docker $REGISTRY --quiet

      # - name: Log in to the Container registry
      #   uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      #   with:
      #     registry: ${{ env.REGISTRY }}
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
